// TypeScript interfaces mirroring Sanity schema types
// These are used by Next.js components — NOT generated by Sanity TypeGen (run later)

export interface SanityEvent {
  _id: string;
  _type: 'event';
  title: string;
  slug: { current: string };
  date: string;
  endDate?: string;
  category: 'UIA Forum' | 'Government Mission' | 'Sector Symposium' | 'EAC Summit' | 'Global Event' | 'Webinar';
  description?: string;
  location?: string;
  image?: { asset: { url: string }; alt?: string };
  registrationUrl?: string;
  isPublished: boolean;
  resources?: Array<{ title: string; file?: { asset: { url: string } }; url?: string }>;
}

export interface SanityLicenseProject {
  _id: string;
  _type: 'licenseProject';
  companyName: string;
  referenceNumber?: string;
  sector?: string;
  subSector?: string;
  region?: string;
  district?: string;
  location?: string;
  coordinates?: { lat: number; lng: number };
  investmentValueUSD?: number;
  investmentValueRange?: string;
  employmentLocal?: number;
  employmentForeign?: number;
  status: 'Licensed' | 'Operational' | 'Under Construction' | 'Suspended' | 'Cancelled';
  licenseDate?: string;
  fiscalYear?: string;
  nationality?: string;
  isIndustrialPark?: boolean;
  industrialParkName?: string;
}

export interface SanityAgency {
  _id: string;
  _type: 'agency';
  name: string;
  code?: 'UIA' | 'URSB' | 'URA' | 'DCIC' | 'NEMA' | 'KCCA' | 'LANDS' | 'UNBS' | 'ERA';
  description?: string;
  contactEmail?: string;
  contactPhone?: string;
  website?: string;
  logo?: { asset: { url: string } };
  services?: string[];
  slaResponseHours?: number;
}

export interface SanityTicket {
  _id: string;
  _type: 'ticket';
  referenceNumber: string;
  title: string;
  description: string;
  category: 'general_inquiry' | 'procedure_query' | 'application_support' | 'license_delay' | 'complaint' | 'vip';
  priority: 'low' | 'medium' | 'high' | 'critical';
  status: 'NEW' | 'ASSIGNED' | 'IN_PROGRESS' | 'PENDING_EXTERNAL' | 'RESOLVED' | 'CLOSED';
  contactName: string;
  contactEmail: string;
  contactPhone?: string;
  investorNationality?: string;
  sector?: string;
  investmentSize?: string;
  assignee?: string;
  assignedAgency?: SanityAgency;
  slaDeadlineHours?: number;
  slaDeadlineAt?: string;
  satisfactionRating?: number;
  satisfactionComment?: string;
  documents?: Array<{ asset: { url: string } }>;
  isEscalated: boolean;
  createdAt: string;
  resolvedAt?: string;
  closedAt?: string;
}

export interface SanityTicketMessage {
  _id: string;
  _type: 'ticketMessage';
  ticket: { _ref: string };
  content: string;
  authorName: string;
  authorRole: 'investor' | 'officer' | 'system';
  authorEmail?: string;
  attachments?: Array<{ asset: { url: string } }>;
  sentAt: string;
  isInternal: boolean;
}

export interface SanityAnalyticsMetadata {
  _id: string;
  period: string;
  totalInquiries?: number;
  resolvedInquiries?: number;
  avgResolutionHours?: number;
  slaComplianceRate?: number;
  satisfactionAverage?: number;
  inquiriesByRegion?: Array<{ region: string; count: number }>;
  inquiriesBySector?: Array<{ sector: string; count: number }>;
  funnelData?: {
    inquiries: number;
    facilitation: number;
    applications: number;
    licensing: number;
    operational: number;
  };
}

export interface SanityDashboardConfig {
  _id: string;
  key: string;
  label?: string;
  value?: string;
  numericValue?: number;
  alertThreshold?: number;
  isActive: boolean;
  metadata?: string;
}

export interface SanityAgencyProfile {
  _id: string;
  name: string;
  email: string;
  agency: SanityAgency;
  role?: 'Officer' | 'Senior Officer' | 'Manager' | 'Director';
  isActive: boolean;
  sanityUserId?: string;
}

export interface SanityInvestorProfile {
  _id: string;
  _type: 'investorProfile';
  referenceNumber: string;
  name: string;
  email: string;
  phone: string;
  nationality: string;
  companyName?: string;
  position?: string;
  investorType?: 'individual' | 'institutional' | 'foreign';
  experience?: 'beginner' | 'intermediate' | 'advanced';
  investmentGoal?: 'growth' | 'income' | 'diversification' | 'strategic';
  investmentAmount?: string;
  timeHorizon?: 'short-term' | 'medium-term' | 'long-term';
  riskTolerance?: 'conservative' | 'moderate' | 'aggressive';
  primarySector?: string;
  secondarySectors?: string[];
  specificInterests?: string;
  capitalSource?: 'savings' | 'loan' | 'partnership' | 'grant';
  timeframe?: 'immediate' | '3-months' | '6-months' | '1-year';
  supportNeeded?: ('legal' | 'financial' | 'technical' | 'marketing')[];
  status?: 'new' | 'contacted' | 'active' | 'inactive';
  createdAt?: string;
}

export interface SanityAdminUser {
  _id: string;
  _type: 'adminUser';
  name: string;
  email: string;
  passwordHash?: string;
  role: 'admin';
  isActive: boolean;
}

export interface SanityAgencyMessage {
  _id: string;
  _type: 'agencyMessage';
  channel: string;
  content: string;
  senderName: string;
  senderAgencyCode?: string;
  senderEmail?: string;
  attachments?: Array<{ asset: { url: string } }>;
  isInternal: boolean;
  sentAt: string;
}

export interface SanityChatEnquiry {
  _id: string;
  _type: 'chatEnquiry';
  sessionId: string;
  userName?: string;
  userEmail?: string;
  userPhone?: string;
  userLocation?: string;
  userMessage: string;
  botResponse: string;
  language: 'en' | 'fr' | 'ar' | 'zh' | 'sw';
  sentiment?: 'positive' | 'neutral' | 'negative';
  tier: 'ai' | 'kb' | 'suggestions';
  createdAt: string;
}
