import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'ticket',
  title: 'Ticket',
  type: 'document',
  fields: [
    defineField({
      name: 'referenceNumber',
      title: 'Reference Number',
      type: 'string',
      description: 'Format: UIA-YYYY-NNNN',
      validation: r => r.required(),
    }),
    defineField({ name: 'title', title: 'Title', type: 'string', validation: r => r.required() }),
    defineField({ name: 'description', title: 'Description', type: 'text', validation: r => r.required() }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      options: { list: ['general_inquiry', 'procedure_query', 'application_support', 'license_delay', 'complaint', 'vip'] },
      validation: r => r.required(),
    }),
    defineField({
      name: 'priority',
      title: 'Priority',
      type: 'string',
      options: { list: ['low', 'medium', 'high', 'critical'] },
      initialValue: 'medium',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: { list: ['NEW', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_EXTERNAL', 'RESOLVED', 'CLOSED'] },
      initialValue: 'NEW',
      validation: r => r.required(),
    }),
    defineField({ name: 'contactName', title: 'Investor Name', type: 'string', validation: r => r.required() }),
    defineField({ name: 'contactEmail', title: 'Investor Email', type: 'email', validation: r => r.required() }),
    defineField({ name: 'contactPhone', title: 'Contact Phone', type: 'string' }),
    defineField({ name: 'investorNationality', title: 'Investor Nationality', type: 'string' }),
    defineField({ name: 'sector', title: 'Sector of Interest', type: 'string' }),
    defineField({ name: 'investmentSize', title: 'Investment Size (USD)', type: 'string' }),
    defineField({ name: 'assignee', title: 'Assigned To', type: 'string' }),
    defineField({ name: 'assignedAgency', title: 'Assigned Agency', type: 'reference', to: [{ type: 'agency' }] }),
    defineField({ name: 'slaDeadlineHours', title: 'SLA Hours', type: 'number' }),
    defineField({ name: 'slaDeadlineAt', title: 'SLA Deadline', type: 'datetime' }),
    defineField({
      name: 'satisfactionRating',
      title: 'Satisfaction Rating',
      type: 'number',
      description: '1-5 rating after resolution',
    }),
    defineField({ name: 'satisfactionComment', title: 'Satisfaction Comment', type: 'text' }),
    defineField({ name: 'documents', title: 'Attached Documents', type: 'array', of: [{ type: 'file' }] }),
    defineField({ name: 'isEscalated', title: 'Escalated', type: 'boolean', initialValue: false }),
    defineField({ name: 'escalatedAt', title: 'Escalated At', type: 'datetime' }),
    defineField({ name: 'createdAt', title: 'Created At', type: 'datetime' }),
    defineField({ name: 'resolvedAt', title: 'Resolved At', type: 'datetime' }),
    defineField({ name: 'closedAt', title: 'Closed At', type: 'datetime' }),
  ],
  preview: { select: { title: 'referenceNumber', subtitle: 'status' } },
});
